In [1]:
import pandas as pd

In [7]:
jan_file= "201701-citibike-tripdata.csv"
july_file= "201707-citibike-tripdata.csv"

In [9]:
jan_df = pd.read_csv(jan_file)
july_df = pd.read_csv(july_file)

In [13]:
jan_df.columns

Index(['Trip Duration', 'Start Time', 'Stop Time', 'Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID', 'User Type',
       'Birth Year', 'Gender'],
      dtype='object')

In [14]:
july_df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [15]:
july_df.columns=['Trip Duration', 'Start Time', 'Stop Time', 'Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID', 'User Type',
       'Birth Year', 'Gender']

In [16]:
july_df.columns

Index(['Trip Duration', 'Start Time', 'Stop Time', 'Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID', 'User Type',
       'Birth Year', 'Gender'],
      dtype='object')

In [17]:
combined_df = pd.concat([jan_df,july_df])

In [18]:
combined_df.columns

Index(['Trip Duration', 'Start Time', 'Stop Time', 'Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID', 'User Type',
       'Birth Year', 'Gender'],
      dtype='object')

In [19]:
combined_df

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,680,2017-01-01 00:00:21,2017-01-01 00:11:41,3226,W 82 St & Central Park West,40.782750,-73.971370,3165,Central Park West & W 72 St,40.775794,-73.976206,25542,Subscriber,1965.0,2
1,1282,2017-01-01 00:00:45,2017-01-01 00:22:08,3263,Cooper Square & E 7 St,40.729236,-73.990868,498,Broadway & W 32 St,40.748549,-73.988084,21136,Subscriber,1987.0,2
2,648,2017-01-01 00:00:57,2017-01-01 00:11:46,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,18147,Customer,NaN,0
3,631,2017-01-01 00:01:10,2017-01-01 00:11:42,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,21211,Customer,NaN,0
4,621,2017-01-01 00:01:25,2017-01-01 00:11:47,3143,5 Ave & E 78 St,40.776829,-73.963888,3152,3 Ave & E 71 St,40.768737,-73.961199,26819,Customer,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1735594,560,2017-07-31 23:59:33,2017-08-01 00:08:53,3260,Mercer St & Bleecker St,40.727064,-73.996621,236,St Marks Pl & 2 Ave,40.728419,-73.987140,16126,Subscriber,1990.0,2
1735595,272,2017-07-31 23:59:35,2017-08-01 00:04:08,247,Perry St & Bleecker St,40.735354,-74.004831,434,9 Ave & W 18 St,40.743174,-74.003664,27684,Subscriber,1999.0,1
1735596,1211,2017-07-31 23:59:37,2017-08-01 00:19:49,3303,Butler St & Court St,40.684989,-73.994403,3308,Kane St & Clinton St,40.686176,-73.996453,28402,Subscriber,1975.0,2
1735597,547,2017-07-31 23:59:48,2017-08-01 00:08:56,276,Duane St & Greenwich St,40.717488,-74.010455,127,Barrow St & Hudson St,40.731724,-74.006744,30150,Subscriber,1992.0,1
1735598,1816,2017-07-31 23:59:57,2017-08-01 00:30:13,3091,Frost St & Meeker St,40.717640,-73.948820,258,DeKalb Ave & Vanderbilt Ave,40.689407,-73.968855,19643,Customer,NaN,0

In [20]:
combined_df.to_csv("citibike.csv",index =False)